name: parkingson_key
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_size_text: ^3.0.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/static/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_mono/static/RobotoMono-Bold.ttf
          weight: 700
